<?php

declare(strict_types=1);

namespace App\Services\Exam;

use App\Models\ExamCategory;
use App\Models\User;

final class ExamCreationService
{
    /**
     * @param  array<string, mixed>  $validated
     * @return array<string, mixed>
     */
    public function prepareData(array $validated, User $user): array
    {
        $data = $validated;
        $data['created_by'] = $user->id;

        $data['status'] = $data['status'] ?? config('exam.defaults.status', 'published');
        $data['total_questions'] = $data['total_questions'] ?? (int) config('exam.defaults.total_questions', 0);
        $data['price'] = $data['price'] ?? (int) config('exam.defaults.price', 0);
        $data['has_negative_marking'] = $data['has_negative_marking'] ?? (bool) config('exam.defaults.has_negative_marking', false);
        $data['negative_mark_ratio'] = $data['negative_mark_ratio']
            ?? (float) config('exam.scoring.default_negative_mark_ratio', 0.3333);

        // Slug is generated by HasUniqueSlug / ExamObserver on creating.
        if (! isset($data['slug']) || blank($data['slug'])) {
            unset($data['slug']);
        }

        if (empty($data['category_id'])) {
            $data['category_id'] = ExamCategory::query()->firstOrCreate(
                ['slug' => 'general'],
                [
                    'name' => 'عمومی',
                    'icon' => 'book',
                ]
            )->id;
        }

        return $data;
    }
}
